WITH TOTAL AS (SELECT NAME, COUNT(NAME) TOTAL_COUNT FROM ANIMAL_INS
GROUP BY NAME) 

SELECT DISTINCT(A.NAME) NAME, TOTAL_COUNT COUNT
FROM ANIMAL_INS A JOIN TOTAL B
ON A.NAME = B.NAME
WHERE B.TOTAL_COUNT >= 2
ORDER BY A.NAME