with MAX_SIZE_TABLE as (
    select YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) as MAX_SIZE
    from ECOLI_DATA
    group by YEAR(DIFFERENTIATION_DATE)
)

select B.YEAR, (B.MAX_SIZE - A.SIZE_OF_COLONY) AS YEAR_DEV, A.ID
from ECOLI_DATA AS A
JOIN MAX_SIZE_TABLE AS B
ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY B.YEAR ASC, YEAR_DEV ASC